name: Plugin Validation

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 8

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Maestro
        run: |
          curl -Ls --retry 3 --retry-all-errors "https://get.maestro.mobile.dev" | bash
          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
          echo -n "e2e" > ${HOME}/.maestro/uuid

      - name: Download samples
        run: |
          maestro download-samples

      - name: Run Android test
        uses: mobile-dev-inc/action-maestro-cloud@v1.9.6
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: samples/wikipedia.apk
          workspace: samples
          include-tags: advanced
        
      - name: Run iOS test
        uses: mobile-dev-inc/action-maestro-cloud@v1.9.6
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: samples/wikipedia.zip
          workspace: samples
          include-tags: advanced
          timeout: 180
